name: Reusable CI Pipeline

on:
  workflow_call:
    inputs:
      node-versions:
        required: false
        type: string
        default: '["20", "22"]'

      run-lint:
        required: false
        type: boolean
        default: true

    outputs:
      build-status:
        description: "Resultado de la construcción"
        value: ${{ jobs.build.outputs.status }}

jobs:

  test-matrix:
    name: Test Node.js v${{ matrix.node }}
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: backend

    strategy:
      fail-fast: false

      matrix:
        node: ${{ fromJson(inputs.node-versions) }}

    steps:

      - name: Checkout del código
        uses: actions/checkout@v5

      - name: Configurar Node.js v${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        if: ${{ inputs.run-lint }}
        run: npm run lint --if-present

      - name: Ejecutar pruebas
        run: npm test --if-present -- --coverage

      - name: Subir reporte de cobertura
        uses: actions/upload-artifact@v5
        with:
          name: coverage-node-${{ matrix.node }}
          path: backend/coverage/
          if-no-files-found: ignore
          retention-days: 7


  build:
    name: Build & Package

    needs: test-matrix

    runs-on: ubuntu-24.04

    outputs:
      status: ${{ steps.set-output.outputs.status }}

    steps:

      - name: Checkout del código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependencias y compilar backend
        working-directory: backend
        run: |
          npm ci
          npm run build --if-present

      - name: Guardar artifact de producción
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact
          path: |
            backend/
            frontend/
          retention-days: 7

      - name: Marcar build como exitoso
        id: set-output
        run: echo "status=success" >> "$GITHUB_OUTPUT"